env:
  RUBY_VERSION: 2.6.6
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: postgres

name: Rails Tests
on: [push,pull_request]

jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build docker services
        run: docker-compose up -d
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '120s'
      - name: Check running servicies
        run: docker ps -a
      # - name: Create database
      #   run: |
      #     bundler exec rails webpacker:install
      #     bundler exec rails db:create RAILS_ENV=ci_test
      #     bundler exec rails db:migrate RAILS_ENV=ci_test
      # - name: Run tests
      #   run: bundler exec rspec spec
      # - name: Upload coverage results    
      #   uses: actions/upload-artifact@master
      #   if: always()
      #   with:
      #     name: coverage-report
      #     path: coverage
      #     retention-days: 5
